# Generated by Django 5.0.6 on 2024-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=9)),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('genero', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=20)),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
